### ISSUE TITLE
Adult content

### ISSUE THREAD

**Issue by novaidea** [jochemstoel/bing-search-php#1]
Hi,
How to restrict adult content ?

$host = "http://www.bing.com/search?q=".$this->query."&safe=active&count=30&format=rss";
not work ;(

**Comment by jochemstoel** [comment]
Hi, Novaidea and thank you for your message. 
I have added an second 'strict mode' parameter to the class constructor and updated the repository. The url parameter you were looking for was not 'safe=active' but actually 'adlt=strict'. Download the latest version and read the updated readme. Let  me  know if it works!

Example 1 | safe mode disabled (default!)

```js
$search = new Bing('teen', false); // false means no safe mode
print_r($search->data);
```

Example 2 | safe mode enabled (true)

```js
$search = new Bing('teen', true); 
print_r($search->data); // this will not have teen sex results :(
```

Follow me and keep in touch!
